#load_main_model: true
save_model: true
model:
  type: resnet50
dataset: imagenet
aug: randaugment
augmentation_search_space: fixed_standard # they used 224 x 244
randaug:
  N: 102
  M: 102   # from appendix
cutout: -1
batch: 512
gpus: 2
epoch: 270
lr: .1
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 8.0
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
test_interval: 20
ood_t: 1.0
temp: 1
warmup_epoch: 54
strong_randaug:
  N: 0
  M: 0    # from appendix
  weights: [0,1.0,1.0,1.0,1.0,1.0,1.0]
