#load_main_model: true
save_model: true
model:
  type: resnet50
dataset: imagenet
aug: DeepAA
deepaa:
  EXP: imagenet_1
augmentation_search_space: Not_used
cutout: -1
batch: 64
gpus: 2
epoch: 270
lr: .1
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 8.0
    epoch: 5
optimizer:
  type: sgd
  nesterov: Tru
  decay: 0.0001
  clip: 0
test_interval: 20
ood_t: 1.0
temp: 1000
warmup_epoch: 40
strong_randaug:
  N: 0
  M: 0    # from appendix
  weights: [0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]

