model:
  type: wresnet28_10
dataset: cifar10
aug: DeepAA
deepaa:
  EXP: cifar_2
cutout: -1
batch: 128
gpus: 1
augmentation_search_space: fix_Not_used # fixed_standard
epoch: 200
lr: 0.1
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.00025
ood_t: 1.0
temp: 1000
warmup_epoch: 40
strong_randaug:
  N: 0
  M: 0    # from appendix
  weights: [0,1.0,1.0,1.0,1.0,1.0,1.0]

